# Cloudflare Pages configuration (recommended for Next.js)
name = "steam-tierlist-maker"
compatibility_date = "2024-09-23"

# Environment variables
[vars]
NEXT_PUBLIC_APP_URL = "https://steam-tierlist-maker.pages.dev"

# To set secrets (like Steam API key), use:
# wrangler secret put STEAM_API_KEY --project steam-tierlist-maker